### ISSUE TITLE
lack of clarity about where to find all of the codelabs

### ISSUE THREAD

**Issue by MarcusJT** [googlecodelabs/about#5]
It's not clear whether https://www.code-labs.io/ contains all of the codelabs featured in sub-sites like https://www.code-labs.io/polytechnic, https://www.code-labs.io/android-dev-summit, https://www.code-labs.io/babbq-2015, https://www.code-labs.io/chrome-dev-summit and so on.

If so, then the sub-sites (and individual codelabs themselves) should link back to the main site with a link saying something like "These and many more codelabs covering a wider range of topics are available at https://www.code-labs.io" so that someone exploring one of them can find the rest

If not, then how is anyone supposed to be able to find all of the codelabs? I've been Googling for "www.code-labs.io" to find the sub-sites but perhaps there are more I didn't find. Surely as a rule all of the codelabs in sub-sites should also be featured in the main/root site?

**Comment by MarcusJT** [comment]
Two further issues add to the confusion:
1. I've noticed that the codelab "Add Voice Interactions to Your App" does appears on https://www.code-labs.io/android-dev-summit with an Android icon, but on https://www.code-labs.io/ it appears with a Search icon. It appears that they are both correctly given the class "category-search" and data-category="Search" but only the latter is rendered using the correct icon.
2. The codelabs at https://www.code-labs.io/ are grouped by category but are not sorted within each group, or at least they appear randomly ordered, perhaps in the order they were added, but there's no date. Why not at least sort them alphabetically within each group?

**Comment by x1ddos** [comment]
This is by design. In android-dev-summit, the codelabs are organized in a way more meaningful for that specific event. On the main index page, codelabs.developers.google.com, we have many categories, so the codelab has a "main" category icon.

Re: where to find all codelabs: codelabs.developers.google.com. That's it. All the event pages are specific to the events. Some are public, others are not. Either way, those are always a subset of codelabs found on the homepage.
